using System.Collections.Generic;
using Core.Effects;
using Core.Occupants;
using UnityEngine;

namespace Core.Scheduling
{
    /// Represents a group of independent enemy actions scheduled to animate simultaneously
    /// within an allocated time slice duration.
    public class AnimationBatch
    {
        /// Zero-based index of this batch in the turn sequence (0, 1, 2...).
        public int BatchIndex { get; set; }

        /// Time duration in seconds allotted for playing this animation batch.
        public float Duration { get; set; }

        /// Actions scheduled to run concurrently in this batch.
        public List<EnactedEnemyAction> Actions { get; } = new List<EnactedEnemyAction>();

        /// Flattened list of all visual effects generated by actions in this batch,
        /// ready for sequential or concurrent dispatch by EffectsQueueRunner.
        public List<BoardEffect> AllEffects
        {
            get
            {
                var effects = new List<BoardEffect>();
                foreach (var action in Actions)
                {
                    if (action?.EmittedEffects != null)
                    {
                        effects.AddRange(action.EmittedEffects);
                    }
                }
                return effects;
            }
        }

        public AnimationBatch(int batchIndex = 0, float duration = 0f)
        {
            BatchIndex = batchIndex;
            Duration = duration;
        }

        /// Appends an enacted enemy action to this concurrent batch.
        public void AddAction(EnactedEnemyAction action)
        {
            if (action != null)
            {
                Actions.Add(action);
            }
        }

        /// Checks whether any action in this batch traverses, originates on, ends on, or affects the specified tile.
        public bool AffectsTile(Vector2Int tile)
        {
            foreach (var action in Actions)
            {
                if (action == null) continue;
                if (action.StartTile == tile || action.EndTile == tile) return true;
                if (action.TraversedTiles != null && action.TraversedTiles.Contains(tile)) return true;
            }
            return false;
        }

        /// Returns the set of all tiles traversed or affected by all actions in this batch.
        public HashSet<Vector2Int> GetAllAffectedTiles()
        {
            var tiles = new HashSet<Vector2Int>();
            foreach (var action in Actions)
            {
                if (action == null) continue;
                tiles.Add(action.StartTile);
                tiles.Add(action.EndTile);
                if (action.TraversedTiles != null)
                {
                    foreach (var t in action.TraversedTiles)
                    {
                        tiles.Add(t);
                    }
                }
            }
            return tiles;
        }

        /// Returns all occupant IDs involved in this batch (acting enemies, blockers, damaged occupants).
        public HashSet<int> GetAllAffectedOccupantIds()
        {
            var ids = new HashSet<int>();
            foreach (var action in Actions)
            {
                if (action == null) continue;
                if (action.Enemy != null) ids.Add(action.Enemy.Id);
                if (action.BlockerOccupantId.HasValue) ids.Add(action.BlockerOccupantId.Value);

                if (action.EmittedEffects != null)
                {
                    foreach (var effect in action.EmittedEffects)
                    {
                        if (effect.OccupantId > 0) ids.Add(effect.OccupantId);
                    }
                }
            }
            return ids;
        }

        /// Checks whether the specified enemy is acting in this batch.
        public bool ContainsEnemy(int enemyId)
        {
            foreach (var action in Actions)
            {
                if (action?.Enemy != null && action.Enemy.Id == enemyId)
                {
                    return true;
                }
            }
            return false;
        }

        /// Checks whether the specified enemy occupant is acting in this batch.
        public bool ContainsEnemy(EnemyOccupant enemy)
        {
            if (enemy == null) return false;
            return ContainsEnemy(enemy.Id);
        }

        /// Checks whether a candidate action has any spatial or path conflict with any action already in this batch.
        public bool HasSpatialConflictWith(EnactedEnemyAction candidate)
        {
            if (candidate == null) return false;

            foreach (var existing in Actions)
            {
                if (TurnBatchScheduler.HasSpatialConflict(existing, candidate))
                {
                    return true;
                }
            }
            return false;
        }

        public override string ToString()
        {
            return $"AnimationBatch #{BatchIndex} (Duration: {Duration:F3}s, Actions: {Actions.Count}, Effects: {AllEffects.Count})";
        }
    }
}
