using System;
using System.Collections.Generic;
using Core.Effects;
using UnityEngine;

namespace Core.Occupants
{
    /// Abstract base data model for any entity that occupies a grid cell on the GameBoard.
    /// 
    /// Strict Architectural Rule:
    /// Every TileOccupant exclusively occupies its cell. Nothing on the board is passable!
    /// No physics colliders or Rigidbodies are used; live spatial occupancy is tracked in GameBoard.
    public abstract class TileOccupant
    {
        private static int _nextId = 1;

        /// Unique identifier for this occupant instance, used to bind simulation data to presentation views.
        public int Id { get; }

        /// Authoritative discrete grid position of this occupant on the GameBoard.
        public Vector2Int GridPosition { get; set; }

        /// Current health points of the occupant.
        public int CurrentHealth { get; protected set; }

        /// Maximum health points of the occupant.
        public int MaxHealth { get; protected set; }

        /// Whether this occupant can be displaced by incoming attacks.
        /// STRICT RULE: True ONLY for PlayerOccupant! All other units, chests, props, and obstacles return false.
        public bool IsPushable { get; protected set; }

        /// True if the occupant's health has reached zero.
        public virtual bool IsDead => CurrentHealth <= 0;

        /// Optional debug/display name.
        public string Name { get; protected set; }

        // Events for observation
        public event Action<TileOccupant, int, TileOccupant> OnDamaged;
        public event Action<TileOccupant> OnDied;

        protected TileOccupant(int maxHealth, Vector2Int initialPosition = default, int id = 0, string name = null)
        {
            Id = id > 0 ? id : _nextId++;
            MaxHealth = Math.Max(1, maxHealth);
            CurrentHealth = MaxHealth;
            GridPosition = initialPosition;
            IsPushable = false; // Default: impassable and immovable by push attacks
            Name = name ?? GetType().Name;
        }

        /// Applies damage to this occupant and generates visual effects.
        /// Subclasses may override to trigger unique effects (e.g. chest opening, prop shattering).
        /// <param name="damage">Amount of damage to inflict.</param>
        /// <param name="source">The occupant causing the damage, if any.</param>
        /// <returns>List of visual effects generated by this damage event.</returns>
        public virtual List<BoardEffect> TakeDamage(int damage, TileOccupant source = null)
        {
            var effects = new List<BoardEffect>();
            if (IsDead || damage <= 0) return effects;

            int applied = Math.Min(damage, CurrentHealth);
            CurrentHealth -= applied;

            OnDamaged?.Invoke(this, applied, source);

            if (IsDead)
            {
                OnDied?.Invoke(this);
            }

            return effects;
        }

        /// Restores health up to MaxHealth.
        public virtual void Heal(int amount)
        {
            if (IsDead || amount <= 0) return;
            CurrentHealth = Math.Min(MaxHealth, CurrentHealth + amount);
        }

        /// Resets the static ID generator counter (useful for unit tests and clean level reloads).
        public static void ResetIdCounter(int startingId = 1)
        {
            _nextId = startingId;
        }

        public override string ToString()
        {
            return $"{Name} [ID:{Id}] at {GridPosition} (HP: {CurrentHealth}/{MaxHealth})";
        }
    }
}
